### ISSUE TITLE
Feature: add image loader example

### ISSUE THREAD

**Issue by Zorgatone** [cmackay/ionic-webpack#3]
If you can add an example of loading images: inside html, js, css and sass/scss

**Comment by Zorgatone** [comment]
Do I just need to replace the image url with `"file!./file.jpg"` instead of `"file.jpg"`?

**Comment by cmackay** [comment]
typically if I am referring to files I would just use the relative path so "./file.jpg" if it is in the same directory. But this may depend on what you are trying to do. Also I have another starter project for webpack and ionic at: https://github.com/cmackay/hybrid-boilerplate  It may have some additional examples in it.

**Comment by Zorgatone** [comment]
I'm having issue with image a in a parent folder..
I will try to see what's wrong in my code


## 

Inviato da Gmail Mobile

**Comment by Zorgatone** [comment]
solved
